---
- name: update motd file
  hosts: myvmlab
  become: true
  user: instructor
  vars:
    apache_version: 2.6
    motd_warning: "WARNING: used by ICT faculty/students only.\n"
    testserver: yes
  tasks:
    - name: setup a MOTD
      copy:
        dest: /etc/motd
        content: "This message was updated via Ansible on {{ ansible_date_time.date }}.\n"

